### ISSUE TITLE
Debug and Quick Log Problems.

### ISSUE THREAD

**Issue by clikdude** [joeferraro/MavensMate-SublimeText#308]
Mac OS X: 10.9.1
Sublime Text: 3 build 3059
Mavensmate: 0.38.0
mm Plugin: v3.4.3

--------------------------------

Clicking on "New Debug Log..." results in:

```                                                                          
Operation: Opening debug log interface (this could take a while...)
Timestamp: Wed, 05 Feb 2014 16:50:01
   Result: [OPERATION FAILED]: 'NoneType' object has no attribute 'user_id'
```

NEW Debug Log was working in 0.37.0/v3.35.

--------------------------------

Clicking on "New Quick Log..." results in:

```
Operation: Setting up logs for debug users (logs can be configured in project/config/.debug)
Timestamp: Wed, 05 Feb 2014 16:50:18
   Result: Success
```

That looks fine, and here is the config/.debug file:

```
{
    "levels": {
        "Workflow": "INFO", 
        "Callout": "INFO", 
        "System": "DEBUG", 
        "Database": "INFO", 
        "ApexCode": "DEBUG", 
        "Validation": "INFO", 
        "Visualforce": "DEBUG"
    }, 
    "users": [
        "<OBSCUREDFORSECURITY>"
    ], 
    "expiration": 60
}
```

Here is the ST console:
```
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_quick_log
[MAVENSMATE]: {}
[MAVENSMATE]: executing mm terminal call:
[MAVENSMATE]: /Applications/MavensMate.app/Contents/Resources/mm/mm -o new_quick_log -c SUBLIME_TEXT_3
[MAVENSMATE]: {"project_name": "sort on SFULL", "workspace": "/Users/yuriz/Workspaces/mavensmate"}
[MAVENSMATE]: response from mm: {"body": "1 Log(s) created successfully", "body_type": "text", "success": true, "time": "1.5407421588897705"}
```

On the Full Sandbox Org, there are no log definitions for the user, and when clicking on "Fetch Logs" nothing is returned.

```
Operation: Fetching Apex Logs (will be placed in project/debug/logs)
Timestamp: Wed, 05 Feb 2014 16:51:19
   Result: Success
```

Here is the ST console:
```
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: fetch_logs
[MAVENSMATE]: {}
[MAVENSMATE]: executing mm terminal call:
[MAVENSMATE]: /Applications/MavensMate.app/Contents/Resources/mm/mm -o fetch_logs -c SUBLIME_TEXT_3
[MAVENSMATE]: {"project_name": "sort on SFULL", "workspace": "/Users/yuriz/Workspaces/mavensmate"}
[MAVENSMATE]: response from mm: {"body": "0 Logs successfully downloaded", "body_type": "text", "success": true, "time": "1.406662940979004"}
```

Quick log was working in 0.37.0/v3.35.

Hope that information helps. Let me know.
