### ISSUE TITLE
'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by kbord** [joeferraro/MavensMate-SublimeText#426]
After updating to 0.38.6, can no longer Deploy to Server.  On Validation step, the following error is returned: 'NoneType' object has no attribute '__getitem__'
Running Sublime Text 3, MavensMate 0.38.6, Mac OS X 10.9.3.

**Comment by RobertGAlexander** [comment]
I still get this error even after toggling mm_compare_before_deployment to false.

**Comment by chrisys** [comment]
I'm trying to setup MavensMate for the first time and coming up against this error. I have tried toggling mm_compare_befoe_deployment as suggested above but it doesn't make any difference in my situation.

Running Sublime Text 3, MM v4.0.5, OSX 10.9.5.

I have successfully used MM before for writing Apex/Tests but this is the first time I have used it to deploy. Situation is I have created a project which is now in Git, I have linked the MM project to my Sandbox and have subscribed to all metadata. I am now trying to deploy to my (fresh) developer account and encountering the issue. MM should be able to do this, right? As in I don't need to use the migration tool to get it up to date first?
